config/routes.rb
Rails.application.routes.draw do
  get 'android_model/index'
root 'updatemodels#index'
  resources :updatemodels

end

app/models/updatemodel.rb
class Updatemodel < ActiveRecord::Base
end

app/controllers/android_model_controller.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'

class AndroidModelController < ApplicationController
  def index
    
    update_start = []
    update_name = []
    update_method = []
    update_term = []
    update_other = []
    
# Updatemodel.destroy_all()
    
    doc = Nokogiri::HTML(open("https://www.nttdocomo.co.jp/support/utilization/product_update/list/index.html?s=date"))
    
#    update_start.push(doc.xpath('//*[@headers="cell-update-start-01"]').text)
#    update_name.push(doc.xpath('//*[@headers="cell-update-start-child-01-01 cell-update-name-01"]').text)
#    update_method.push(doc.xpath('//*[@headers="cell-update-start-child-01-01 cell-update-method-01"]').text)
#    update_term.push(doc.xpath('//*[@headers="cell-update-start-child-01-01 cell-update-term-01"]').text)
#    update_other.push(doc.xpath('//*[@headers="cell-update-start-child-01-01 cell-update-others-01"]').text)
#    render text: update_start[]
  
  doc.xpath('//*[@headers="cell-update-start-01"]').each do |content|
    update_start.push(content.text)
  end
  
    doc.xpath('//*[@headers="cell-update-start-child-01-01 cell-update-name-01"]').each do |content|
    update_name.push(content.text)
  end
  
    doc.xpath('//*[@headers="cell-update-start-child-01-01 cell-update-method-01"]').each do |content|
    update_method.push(content.text)
  end
   
  doc.xpath('//*[@headers="cell-update-start-child-01-01 cell-update-term-01"]').each do |content|
  update_term.push(content.text)
  end
  
  doc.xpath('//*[@headers="cell-update-start-child-01-01 cell-update-others-01"]').each do |content|
    update_other.push(content.text)
  end
      
    for i in 0 .. update_start.length do
      updatemodel = Updatemodel.new(
      update_start: update_start[i], 
      update_name: update_name[i],
      update_method: update_method[i], 
      update_term: update_term[i],
      update_other: update_other[i]
    ) 
      updatemodel.save
      updatemodel.errors.full_messages
    end
    
 render text: update_start
  #  updatemodel.save
  #  updatemodel.errors.full_messages
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/model_insert_controller.rb
class ModelInsertController < ApplicationController
end

app/controllers/parse_controller.rb
class ParseController < ApplicationController
end

app/controllers/updatemodels_controller.rb
class UpdatemodelsController < ApplicationController
  before_action :set_updatemodel, only: [:show, :edit, :update, :destroy]

  # GET /updatemodels
  # GET /updatemodels.json
  def index
    @updatemodels = Updatemodel.all
  end

  # GET /updatemodels/1
  # GET /updatemodels/1.json
  def show
  end

  # GET /updatemodels/new
  def new
    @updatemodel = Updatemodel.new
  end

  # GET /updatemodels/1/edit
  def edit
  end

  # POST /updatemodels
  # POST /updatemodels.json
  def create
    @updatemodel = Updatemodel.new(updatemodel_params)

    respond_to do |format|
      if @updatemodel.save
        format.html { redirect_to @updatemodel, notice: 'Updatemodel was successfully created.' }
        format.json { render :show, status: :created, location: @updatemodel }
      else
        format.html { render :new }
        format.json { render json: @updatemodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updatemodels/1
  # PATCH/PUT /updatemodels/1.json
  def update
    respond_to do |format|
      if @updatemodel.update(updatemodel_params)
        format.html { redirect_to @updatemodel, notice: 'Updatemodel was successfully updated.' }
        format.json { render :show, status: :ok, location: @updatemodel }
      else
        format.html { render :edit }
        format.json { render json: @updatemodel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updatemodels/1
  # DELETE /updatemodels/1.json
  def destroy
    @updatemodel.destroy
    respond_to do |format|
      format.html { redirect_to updatemodels_url, notice: 'Updatemodel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_updatemodel
      @updatemodel = Updatemodel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def updatemodel_params
      params.require(:updatemodel).permit(:update_start, :update_name, :update_method, :update_term, :update_other)
    end
end

app/helpers/android_model_helper.rb
module AndroidModelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/model_insert_helper.rb
module ModelInsertHelper
end

app/helpers/parse_helper.rb
module ParseHelper
end

app/helpers/updatemodels_helper.rb
module UpdatemodelsHelper
end

app/views/android_model/index.html.erb
<h1>AndroidModel#index</h1>
<p>Find me in app/views/android_model/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/updatemodels/_form.html.erb
<%= form_for(@updatemodel) do |f| %>
  <% if @updatemodel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@updatemodel.errors.count, "error") %> prohibited this updatemodel from being saved:</h2>

      <ul>
      <% @updatemodel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :update_start %><br>
    <%= f.text_field :update_start %>
  </div>
  <div class="field">
    <%= f.label :update_name %><br>
    <%= f.text_field :update_name %>
  </div>
  <div class="field">
    <%= f.label :update_method %><br>
    <%= f.text_field :update_method %>
  </div>
  <div class="field">
    <%= f.label :update_term %><br>
    <%= f.text_field :update_term %>
  </div>
  <div class="field">
    <%= f.label :update_other %><br>
    <%= f.text_field :update_other %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/updatemodels/edit.html.erb
<h1>Editing Updatemodel</h1>

<%= render 'form' %>

<%= link_to 'Show', @updatemodel %> |
<%= link_to 'Back', updatemodels_path %>

app/views/updatemodels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ntt docomo Android端末更新情報一覧</h1>

<table>
  <thead>
    <tr>
      <th>更新開始日</th>
      <th>機種名</th>
      <th>対応方法</th>
      <th>更新期間</th>
      <th>その他</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @updatemodels.each do |updatemodel| %>
      <tr>
        <td><%= updatemodel.update_start %></td>
        <td><%= updatemodel.update_name %></td>
        <td><%= updatemodel.update_method %></td>
        <td><%= updatemodel.update_term %></td>
        <td><%= updatemodel.update_other %></td>
        <td><%= link_to 'Show', updatemodel %></td>
        <td><%= link_to 'Edit', edit_updatemodel_path(updatemodel) %></td>
        <td><%= link_to 'Destroy', updatemodel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Updatemodel', new_updatemodel_path %>

app/views/updatemodels/new.html.erb
<h1>New Updatemodel</h1>

<%= render 'form' %>

<%= link_to 'Back', updatemodels_path %>

app/views/updatemodels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Update start:</strong>
  <%= @updatemodel.update_start %>
</p>

<p>
  <strong>Update name:</strong>
  <%= @updatemodel.update_name %>
</p>

<p>
  <strong>Update method:</strong>
  <%= @updatemodel.update_method %>
</p>

<p>
  <strong>Update term:</strong>
  <%= @updatemodel.update_term %>
</p>

<p>
  <strong>Update other:</strong>
  <%= @updatemodel.update_other %>
</p>

<%= link_to 'Edit', edit_updatemodel_path(@updatemodel) %> |
<%= link_to 'Back', updatemodels_path %>